- name: create the ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-021267ece598a730b
    zone_id: "Z0703152351ZHIBULK5Q0"
    domian_name: "thiscomeback.fun"
    instances:
    - mongodb
    - redis
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}" 
      instance_type: t3.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
      tags:
        Name: "{{ item }}"
    loop: "{{instances}}"
    register: ec2_output

  # - name: create the r35 module
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{domian_name}}"
  #     record: "{{item.item}}.{{domian_name}}" #mongodb.thiscomeback.fun
  #     type: A
  #     ttl: 1
  #     value: "{{item.instances[0].private_ip_address}}"
  #     overwrite: true
  #   loop: "{{ec2_output.results}}"


  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ec2_output}}"

  # - name: print the private IP addess
  #   ansible.builtin.debug: 
  #     msg: "{{item.instances[0].private_ip_address}}"
  #   loop: "{{ec2_output.results}}"

  # - name: print the public IP addess
  #   ansible.builtin.debug: 
  #     msg: "{{item.instances[0].public_ip_address}}"
  #   loop: "{{ec2_output.results}}"







 
