- name: setup mongodb server
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: copy mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mono.repo
